from enum import Enum


class TimeUnitValue(str, Enum):
    EPOCH = "EPOCH"
    STEP = "STEP"
    SECOND = "SECOND"
    MINUTE = "MINUTE"
    HOUR = "HOUR"
    NEVER = "NEVER"
    ALWAYS = "ALWAYS"


class GradientReducePrecisionValue(str, Enum):
    WEIGHT_DTYPE = "WEIGHT_DTYPE"
    FLOAT_32 = "FLOAT_32"
    WEIGHT_DTYPE_STOCHASTIC = "WEIGHT_DTYPE_STOCHASTIC"
    FLOAT_32_STOCHASTIC = "FLOAT_32_STOCHASTIC"


class LearningRateSchedulerValue(str, Enum):
    CONSTANT = "CONSTANT"
    LINEAR = "LINEAR"
    COSINE = "COSINE"
    COSINE_WITH_RESTARTS = "COSINE_WITH_RESTARTS"
    COSINE_WITH_HARD_RESTARTS = "COSINE_WITH_HARD_RESTARTS"
    REX = "REX"
    ADAFACTOR = "ADAFACTOR"
    CUSTOM = "CUSTOM"


class LearningRateScalerValue(str, Enum):
    NONE = "NONE"
    BATCH = "BATCH"
    GLOBAL_BATCH = "GLOBAL_BATCH"
    GRADIENT_ACCUMULATION = "GRADIENT_ACCUMULATION"
    BOTH = "BOTH"
    GLOBAL_BOTH = "GLOBAL_BOTH"


class EMAModeValue(str, Enum):
    OFF = "OFF"
    GPU = "GPU"
    CPU = "CPU"


class GradientCheckpointingMethodValue(str, Enum):
    OFF = "OFF"
    ON = "ON"
    CPU_OFFLOADED = "CPU_OFFLOADED"


class TrainingMethodValue(str, Enum):
    FINE_TUNE = "FINE_TUNE"
    LORA = "LORA"
    EMBEDDING = "EMBEDDING"
    FINE_TUNE_VAE = "FINE_TUNE_VAE"


class ModelTypeValue(str, Enum):
    STABLE_DIFFUSION_15 = "STABLE_DIFFUSION_15"
    STABLE_DIFFUSION_15_INPAINTING = "STABLE_DIFFUSION_15_INPAINTING"
    STABLE_DIFFUSION_20 = "STABLE_DIFFUSION_20"
    STABLE_DIFFUSION_20_BASE = "STABLE_DIFFUSION_20_BASE"
    STABLE_DIFFUSION_20_INPAINTING = "STABLE_DIFFUSION_20_INPAINTING"
    STABLE_DIFFUSION_20_DEPTH = "STABLE_DIFFUSION_20_DEPTH"
    STABLE_DIFFUSION_21 = "STABLE_DIFFUSION_21"
    STABLE_DIFFUSION_21_BASE = "STABLE_DIFFUSION_21_BASE"
    STABLE_DIFFUSION_3 = "STABLE_DIFFUSION_3"
    STABLE_DIFFUSION_35 = "STABLE_DIFFUSION_35"
    STABLE_DIFFUSION_XL_10_BASE = "STABLE_DIFFUSION_XL_10_BASE"
    STABLE_DIFFUSION_XL_10_BASE_INPAINTING = "STABLE_DIFFUSION_XL_10_BASE_INPAINTING"
    WUERSTCHEN_2 = "WUERSTCHEN_2"
    STABLE_CASCADE_1 = "STABLE_CASCADE_1"
    PIXART_ALPHA = "PIXART_ALPHA"
    PIXART_SIGMA = "PIXART_SIGMA"
    FLUX_DEV_1 = "FLUX_DEV_1"
    FLUX_FILL_DEV_1 = "FLUX_FILL_DEV_1"
    FLUX_2 = "FLUX_2"
    SANA = "SANA"
    HUNYUAN_VIDEO = "HUNYUAN_VIDEO"
    HI_DREAM_FULL = "HI_DREAM_FULL"
    CHROMA_1 = "CHROMA_1"
    QWEN = "QWEN"
    Z_IMAGE = "Z_IMAGE"


class DataTypeValue(str, Enum):
    NONE = "NONE"
    FLOAT_8 = "FLOAT_8"
    FLOAT_16 = "FLOAT_16"
    FLOAT_32 = "FLOAT_32"
    BFLOAT_16 = "BFLOAT_16"
    TFLOAT_32 = "TFLOAT_32"
    INT_8 = "INT_8"
    NFLOAT_4 = "NFLOAT_4"
    FLOAT_W8A8 = "FLOAT_W8A8"
    INT_W8A8 = "INT_W8A8"
    GGUF = "GGUF"
    GGUF_A8_FLOAT = "GGUF_A8_FLOAT"
    GGUF_A8_INT = "GGUF_A8_INT"


class ImageFormatValue(str, Enum):
    PNG = "PNG"
    JPG = "JPG"


class VideoFormatValue(str, Enum):
    PNG_IMAGE_SEQUENCE = "PNG_IMAGE_SEQUENCE"
    JPG_IMAGE_SEQUENCE = "JPG_IMAGE_SEQUENCE"
    MP4 = "MP4"


class AudioFormatValue(str, Enum):
    MP3 = "MP3"


class NoiseSchedulerValue(str, Enum):
    DDIM = "DDIM"
    EULER = "EULER"
    EULER_A = "EULER_A"
    DPMPP = "DPMPP"
    DPMPP_SDE = "DPMPP_SDE"
    UNIPC = "UNIPC"
    EULER_KARRAS = "EULER_KARRAS"
    DPMPP_KARRAS = "DPMPP_KARRAS"
    DPMPP_SDE_KARRAS = "DPMPP_SDE_KARRAS"
    UNIPC_KARRAS = "UNIPC_KARRAS"


class ModelFormatValue(str, Enum):
    DIFFUSERS = "DIFFUSERS"
    CKPT = "CKPT"
    SAFETENSORS = "SAFETENSORS"
    LEGACY_SAFETENSORS = "LEGACY_SAFETENSORS"
    COMFY_LORA = "COMFY_LORA"
    INTERNAL = "INTERNAL"


class ConfigPartValue(str, Enum):
    NONE = "NONE"
    SETTINGS = "SETTINGS"
    ALL = "ALL"


class ConceptTypeValue(str, Enum):
    STANDARD = "STANDARD"
    VALIDATION = "VALIDATION"
    PRIOR_PREDICTION = "PRIOR_PREDICTION"


class BalancingStrategyValue(str, Enum):
    REPEATS = "REPEATS"
    SAMPLES = "SAMPLES"
